package jspritTest;

import java.io.File;
import java.io.IOException;
import java.util.Collection;

import jsprit.analysis.toolbox.AlgorithmSearchProgressChartListener;
import jsprit.analysis.toolbox.GraphStreamViewer;
import jsprit.analysis.toolbox.StopWatch;
import jsprit.core.algorithm.VehicleRoutingAlgorithm;
import jsprit.core.algorithm.box.Jsprit;
import jsprit.core.algorithm.listener.VehicleRoutingAlgorithmListeners.Priority;
import jsprit.core.problem.VehicleRoutingProblem;
import jsprit.core.problem.VehicleRoutingProblem.FleetSize;
import jsprit.core.problem.io.VrpXMLReader;
import jsprit.core.problem.solution.VehicleRoutingProblemSolution;
import jsprit.core.reporting.SolutionPrinter;
import jsprit.core.util.Solutions;
import jspritTest.util.FilePrintWriter;
import jspritTest.util.Plotter;
import jspritTest.util.VehicleGenerator;

public class TwoDepot400Services {

	public static void main(String... args ){
		VehicleRoutingProblem.Builder vrpBuilder = VehicleRoutingProblem.Builder.newInstance();
		String serviceFileName = "400Services";
		//this file needs to be generated by VRPXMLGenerator first
        new VrpXMLReader(vrpBuilder).read("input/autoGeneratedServiceXML/"+serviceFileName+".xml");
        
        VehicleGenerator vehicleGenerator = new VehicleGenerator(vrpBuilder, "input/vehicleConfig/2Depot.properties");
        vehicleGenerator.generate();
        vrpBuilder.setFleetSize(FleetSize.FINITE); //finite vehicles
        VehicleRoutingProblem vrp = vrpBuilder.build();
        VehicleRoutingAlgorithm vra = Jsprit.Builder.newInstance(vrp).setProperty(Jsprit.Parameter.THREADS, "4").buildAlgorithm();
        vra.getAlgorithmListeners().addListener(new StopWatch(), Priority.HIGH);
        vra.getAlgorithmListeners().addListener(new AlgorithmSearchProgressChartListener("output/autoGenerated/"+serviceFileName+"progress.png"));
        Collection<VehicleRoutingProblemSolution> solutions = vra.searchSolutions();

        SolutionPrinter.print(vrp, Solutions.bestOf(solutions), SolutionPrinter.Print.VERBOSE);
        
        File solutionFile = new File("output/PrintedSolutions/"+serviceFileName+"SolutionTwoDepot.txt");
        try {
			solutionFile.createNewFile();
		} catch (IOException e) {
			e.printStackTrace();
		}
        FilePrintWriter.setup(solutionFile);
        FilePrintWriter.print(vrp, Solutions.bestOf(solutions), FilePrintWriter.Print.VERBOSE);
        FilePrintWriter.tearDown();
        
        new Plotter(vrp, Solutions.bestOf(solutions)).setLabel(Plotter.Label.ID).plot("output/autoGenerated/"+serviceFileName+"_solution.png", serviceFileName);
        new GraphStreamViewer(vrp, Solutions.bestOf(solutions)).setRenderDelay(50).display();
	}
	
}
